import { defineConfig } from "vitepress";

export default defineConfig({
  base: "/golden-palace/",
  title: "Golden Palace",
  description:
    "A personal scripture memorization system built on Hebrew pictographs, gematria, PAO library, and mind palace architecture.",

  themeConfig: {
    nav: [
      { text: "Home", link: "/" },
      { text: "Alphabet", link: "/alphabet/" },
      { text: "Techniques", link: "/techniques/" },
      { text: "Books", link: "/books/" },
      { text: "Gematria", link: "/gematria/" },
      { text: "Tools", link: "/tools/" },
      { text: "GitHub", link: "https://github.com/njncalub/golden-palace" },
    ],

    sidebar: [
      {
        text: "Introduction",
        items: [{ text: "What Is This?", link: "/" }],
      },
      {
        text: "Hebrew Alphabet",
        items: [
          { text: "Getting Started", link: "/alphabet/" },
          { text: "01 - א - Aleph (#1)", link: "/alphabet/01-aleph" },
          { text: "02 - ב - Bet (#2)", link: "/alphabet/02-bet" },
          { text: "03 - ג - Gimel (#3)", link: "/alphabet/03-gimel" },
          { text: "04 - ד - Dalet (#4)", link: "/alphabet/04-dalet" },
          { text: "05 - ה - Hey (#5)", link: "/alphabet/05-hey" },
          { text: "06 - ו - Vav (#6)", link: "/alphabet/06-vav" },
          { text: "07 - ז - Zayin (#7)", link: "/alphabet/07-zayin" },
          { text: "08 - ח - Chet (#8)", link: "/alphabet/08-chet" },
          { text: "09 - ט - Tet (#9)", link: "/alphabet/09-tet" },
          { text: "10 - י - Yod (#10)", link: "/alphabet/10-yod" },
          { text: "11 - כ - Kaf (#20)", link: "/alphabet/11-kaf" },
          { text: "12 - ל - Lamed (#30)", link: "/alphabet/12-lamed" },
          { text: "13 - מ - Mem (#40)", link: "/alphabet/13-mem" },
          { text: "14 - נ - Nun (#50)", link: "/alphabet/14-nun" },
          { text: "15 - ס - Samech (#60)", link: "/alphabet/15-samech" },
          { text: "16 - ע - Ayin (#70)", link: "/alphabet/16-ayin" },
          { text: "17 - פ - Pey (#80)", link: "/alphabet/17-pey" },
          { text: "18 - צ - Tzadi (#90)", link: "/alphabet/18-tzadi" },
          { text: "19 - ק - Kof (#100)", link: "/alphabet/19-kof" },
          { text: "20 - ר - Resh (#200)", link: "/alphabet/20-resh" },
          { text: "21 - ש - Shin (#300)", link: "/alphabet/21-shin" },
          { text: "22 - ת - Tav (#400)", link: "/alphabet/22-tav" },
        ],
      },
      {
        text: "Memory Techniques",
        items: [
          { text: "Overview", link: "/techniques/" },
          { text: "Mind Palace", link: "/techniques/mind-palace" },
          { text: "PAO System", link: "/techniques/pao" },
          { text: "Hebrew Major System", link: "/techniques/major-system" },
          { text: "Spaced Repetition", link: "/techniques/spaced-repetition" },
          { text: "Gematria for Memory", link: "/techniques/gematria" },
        ],
      },
      {
        text: "Verses & Meditations",
        items: [
          { text: "Verse Entries", link: "/verses/" },
          { text: "Visual Meditations", link: "/meditations/" },
        ],
      },
      {
        text: "PAO Library",
        items: [{ text: "Overview", link: "/pao/" }],
      },
      {
        text: "Books of the Bible",
        items: [
          { text: "Overview", link: "/books/" },
          { text: "01 - Genesis", link: "/books/01-genesis" },
          { text: "02 - Exodus", link: "/books/02-exodus" },
          { text: "03 - Leviticus", link: "/books/03-leviticus" },
          { text: "04 - Numbers", link: "/books/04-numbers" },
          { text: "05 - Deuteronomy", link: "/books/05-deuteronomy" },
          { text: "06 - Joshua", link: "/books/06-joshua" },
          { text: "07 - Judges", link: "/books/07-judges" },
          { text: "08 - Ruth", link: "/books/08-ruth" },
          { text: "09 - 1 Samuel", link: "/books/09-1-samuel" },
          { text: "10 - 2 Samuel", link: "/books/10-2-samuel" },
          { text: "11 - 1 Kings", link: "/books/11-1-kings" },
          { text: "12 - 2 Kings", link: "/books/12-2-kings" },
          { text: "13 - 1 Chronicles", link: "/books/13-1-chronicles" },
          { text: "14 - 2 Chronicles", link: "/books/14-2-chronicles" },
          { text: "15 - Ezra", link: "/books/15-ezra" },
          { text: "16 - Nehemiah", link: "/books/16-nehemiah" },
          { text: "17 - Esther", link: "/books/17-esther" },
          { text: "18 - Job", link: "/books/18-job" },
          { text: "19 - Psalms", link: "/books/19-psalms" },
          { text: "20 - Proverbs", link: "/books/20-proverbs" },
          { text: "21 - Ecclesiastes", link: "/books/21-ecclesiastes" },
          { text: "22 - Song of Solomon", link: "/books/22-song-of-solomon" },
          { text: "23 - Isaiah", link: "/books/23-isaiah" },
          { text: "24 - Jeremiah", link: "/books/24-jeremiah" },
          { text: "25 - Lamentations", link: "/books/25-lamentations" },
          { text: "26 - Ezekiel", link: "/books/26-ezekiel" },
          { text: "27 - Daniel", link: "/books/27-daniel" },
          { text: "28 - Hosea", link: "/books/28-hosea" },
          { text: "29 - Joel", link: "/books/29-joel" },
          { text: "30 - Amos", link: "/books/30-amos" },
          { text: "31 - Obadiah", link: "/books/31-obadiah" },
          { text: "32 - Jonah", link: "/books/32-jonah" },
          { text: "33 - Micah", link: "/books/33-micah" },
          { text: "34 - Nahum", link: "/books/34-nahum" },
          { text: "35 - Habakkuk", link: "/books/35-habakkuk" },
          { text: "36 - Zephaniah", link: "/books/36-zephaniah" },
          { text: "37 - Haggai", link: "/books/37-haggai" },
          { text: "38 - Zechariah", link: "/books/38-zechariah" },
          { text: "39 - Malachi", link: "/books/39-malachi" },
          { text: "40 - Matthew", link: "/books/40-matthew" },
          { text: "41 - Mark", link: "/books/41-mark" },
          { text: "42 - Luke", link: "/books/42-luke" },
          { text: "43 - John", link: "/books/43-john" },
          { text: "44 - Acts", link: "/books/44-acts" },
          { text: "45 - Romans", link: "/books/45-romans" },
          { text: "46 - 1 Corinthians", link: "/books/46-1-corinthians" },
          { text: "47 - 2 Corinthians", link: "/books/47-2-corinthians" },
          { text: "48 - Galatians", link: "/books/48-galatians" },
          { text: "49 - Ephesians", link: "/books/49-ephesians" },
          { text: "50 - Philippians", link: "/books/50-philippians" },
          { text: "51 - Colossians", link: "/books/51-colossians" },
          { text: "52 - 1 Thessalonians", link: "/books/52-1-thessalonians" },
          { text: "53 - 2 Thessalonians", link: "/books/53-2-thessalonians" },
          { text: "54 - 1 Timothy", link: "/books/54-1-timothy" },
          { text: "55 - 2 Timothy", link: "/books/55-2-timothy" },
          { text: "56 - Titus", link: "/books/56-titus" },
          { text: "57 - Philemon", link: "/books/57-philemon" },
          { text: "58 - Hebrews", link: "/books/58-hebrews" },
          { text: "59 - James", link: "/books/59-james" },
          { text: "60 - 1 Peter", link: "/books/60-1-peter" },
          { text: "61 - 2 Peter", link: "/books/61-2-peter" },
          { text: "62 - 1 John", link: "/books/62-1-john" },
          { text: "63 - 2 John", link: "/books/63-2-john" },
          { text: "64 - 3 John", link: "/books/64-3-john" },
          { text: "65 - Jude", link: "/books/65-jude" },
          { text: "66 - Revelation", link: "/books/66-revelation" },
        ],
      },
      {
        text: "Gematria Study",
        items: [
          { text: "Getting Started", link: "/gematria/" },
          { text: "Discoveries", link: "/gematria/discoveries" },
        ],
      },
      {
        text: "Tools",
        items: [
          { text: "Overview", link: "/tools/" },
          { text: "Prompts & Study Tools", link: "/tools/prompts" },
        ],
      },
    ],

    socialLinks: [
      { icon: "github", link: "https://github.com/njncalub/golden-palace" },
    ],

    footer: {
      message: "Built with VitePress",
      copyright: "",
    },
  },
});
