import { defineConfig } from "vitepress";

export default defineConfig({
  base: "/golden-palace/",
  title: "Golden Palace",
  description:
    "A personal scripture memorization system built on Hebrew pictographs, gematria, PAO library, and mind palace architecture.",

  themeConfig: {
    nav: [
      { text: "Home", link: "/" },
      { text: "Alphabet", link: "/alphabet/" },
      { text: "Techniques", link: "/techniques/" },
      { text: "Books", link: "/books/" },
      { text: "Gematria", link: "/gematria/" },
      { text: "Tools", link: "/tools/" },
      { text: "GitHub", link: "https://github.com/njncalub/golden-palace" },
    ],

    sidebar: [
      {
        text: "Introduction",
        items: [{ text: "What Is This?", link: "/" }],
      },
      {
        text: "Hebrew Alphabet",
        items: [
          { text: "Getting Started", link: "/alphabet/" },
          { text: "01 - א - Aleph (#1)", link: "/alphabet/01-aleph" },
          { text: "02 - ב - Bet (#2)", link: "/alphabet/02-bet" },
          { text: "03 - ג - Gimel (#3)", link: "/alphabet/03-gimel" },
          { text: "04 - ד - Dalet (#4)", link: "/alphabet/04-dalet" },
          { text: "05 - ה - Hey (#5)", link: "/alphabet/05-hey" },
          { text: "06 - ו - Vav (#6)", link: "/alphabet/06-vav" },
          { text: "07 - ז - Zayin (#7)", link: "/alphabet/07-zayin" },
          { text: "08 - ח - Chet (#8)", link: "/alphabet/08-chet" },
          { text: "09 - ט - Tet (#9)", link: "/alphabet/09-tet" },
          { text: "10 - י - Yod (#10)", link: "/alphabet/10-yod" },
          { text: "11 - כ - Kaf (#20)", link: "/alphabet/11-kaf" },
          { text: "12 - ל - Lamed (#30)", link: "/alphabet/12-lamed" },
          { text: "13 - מ - Mem (#40)", link: "/alphabet/13-mem" },
          { text: "14 - נ - Nun (#50)", link: "/alphabet/14-nun" },
          { text: "15 - ס - Samech (#60)", link: "/alphabet/15-samech" },
          { text: "16 - ע - Ayin (#70)", link: "/alphabet/16-ayin" },
          { text: "17 - פ - Pey (#80)", link: "/alphabet/17-pey" },
          { text: "18 - צ - Tzadi (#90)", link: "/alphabet/18-tzadi" },
          { text: "19 - ק - Kof (#100)", link: "/alphabet/19-kof" },
          { text: "20 - ר - Resh (#200)", link: "/alphabet/20-resh" },
          { text: "21 - ש - Shin (#300)", link: "/alphabet/21-shin" },
          { text: "22 - ת - Tav (#400)", link: "/alphabet/22-tav" },
        ],
      },
      {
        text: "Memory Techniques",
        items: [
          { text: "Overview", link: "/techniques/" },
          { text: "Mind Palace", link: "/techniques/mind-palace" },
          { text: "PAO System", link: "/techniques/pao" },
          { text: "Hebrew Major System", link: "/techniques/major-system" },
          { text: "Spaced Repetition", link: "/techniques/spaced-repetition" },
          { text: "Gematria for Memory", link: "/techniques/gematria" },
        ],
      },
      {
        text: "Verses & Meditations",
        items: [
          { text: "Verse Entries", link: "/verses/" },
          { text: "Visual Meditations", link: "/meditations/" },
        ],
      },
      {
        text: "PAO Library",
        items: [{ text: "Overview", link: "/pao/" }],
      },
      {
        text: "Books of the Bible",
        items: [
          { text: "Overview", link: "/books/" },
          { text: "Genesis", link: "/books/01-genesis" },
          { text: "Exodus", link: "/books/02-exodus" },
          { text: "Leviticus", link: "/books/03-leviticus" },
          { text: "Numbers", link: "/books/04-numbers" },
          { text: "Deuteronomy", link: "/books/05-deuteronomy" },
          { text: "Joshua", link: "/books/06-joshua" },
          { text: "Judges", link: "/books/07-judges" },
          { text: "Ruth", link: "/books/08-ruth" },
          { text: "1 Samuel", link: "/books/09-1-samuel" },
          { text: "2 Samuel", link: "/books/10-2-samuel" },
          { text: "1 Kings", link: "/books/11-1-kings" },
          { text: "2 Kings", link: "/books/12-2-kings" },
          { text: "1 Chronicles", link: "/books/13-1-chronicles" },
          { text: "2 Chronicles", link: "/books/14-2-chronicles" },
          { text: "Ezra", link: "/books/15-ezra" },
          { text: "Nehemiah", link: "/books/16-nehemiah" },
          { text: "Esther", link: "/books/17-esther" },
          { text: "Job", link: "/books/18-job" },
          { text: "Psalms", link: "/books/19-psalms" },
          { text: "Proverbs", link: "/books/20-proverbs" },
          { text: "Ecclesiastes", link: "/books/21-ecclesiastes" },
          { text: "Song of Solomon", link: "/books/22-song-of-solomon" },
          { text: "Isaiah", link: "/books/23-isaiah" },
          { text: "Jeremiah", link: "/books/24-jeremiah" },
          { text: "Lamentations", link: "/books/25-lamentations" },
          { text: "Ezekiel", link: "/books/26-ezekiel" },
          { text: "Daniel", link: "/books/27-daniel" },
          { text: "Hosea", link: "/books/28-hosea" },
          { text: "Joel", link: "/books/29-joel" },
          { text: "Amos", link: "/books/30-amos" },
          { text: "Obadiah", link: "/books/31-obadiah" },
          { text: "Jonah", link: "/books/32-jonah" },
          { text: "Micah", link: "/books/33-micah" },
          { text: "Nahum", link: "/books/34-nahum" },
          { text: "Habakkuk", link: "/books/35-habakkuk" },
          { text: "Zephaniah", link: "/books/36-zephaniah" },
          { text: "Haggai", link: "/books/37-haggai" },
          { text: "Zechariah", link: "/books/38-zechariah" },
          { text: "Malachi", link: "/books/39-malachi" },
          { text: "Matthew", link: "/books/40-matthew" },
          { text: "Mark", link: "/books/41-mark" },
          { text: "Luke", link: "/books/42-luke" },
          { text: "John", link: "/books/43-john" },
          { text: "Acts", link: "/books/44-acts" },
          { text: "Romans", link: "/books/45-romans" },
          { text: "1 Corinthians", link: "/books/46-1-corinthians" },
          { text: "2 Corinthians", link: "/books/47-2-corinthians" },
          { text: "Galatians", link: "/books/48-galatians" },
          { text: "Ephesians", link: "/books/49-ephesians" },
          { text: "Philippians", link: "/books/50-philippians" },
          { text: "Colossians", link: "/books/51-colossians" },
          { text: "1 Thessalonians", link: "/books/52-1-thessalonians" },
          { text: "2 Thessalonians", link: "/books/53-2-thessalonians" },
          { text: "1 Timothy", link: "/books/54-1-timothy" },
          { text: "2 Timothy", link: "/books/55-2-timothy" },
          { text: "Titus", link: "/books/56-titus" },
          { text: "Philemon", link: "/books/57-philemon" },
          { text: "Hebrews", link: "/books/58-hebrews" },
          { text: "James", link: "/books/59-james" },
          { text: "1 Peter", link: "/books/60-1-peter" },
          { text: "2 Peter", link: "/books/61-2-peter" },
          { text: "1 John", link: "/books/62-1-john" },
          { text: "2 John", link: "/books/63-2-john" },
          { text: "3 John", link: "/books/64-3-john" },
          { text: "Jude", link: "/books/65-jude" },
          { text: "Revelation", link: "/books/66-revelation" },
        ],
      },
      {
        text: "Gematria Study",
        items: [
          { text: "Getting Started", link: "/gematria/" },
          { text: "Discoveries", link: "/gematria/discoveries" },
        ],
      },
      {
        text: "Tools",
        items: [
          { text: "Overview", link: "/tools/" },
          { text: "Prompts & Study Tools", link: "/tools/prompts" },
        ],
      },
    ],

    socialLinks: [
      { icon: "github", link: "https://github.com/njncalub/golden-palace" },
    ],

    footer: {
      message: "Built with VitePress",
      copyright: "",
    },
  },
});
