import { defineConfig } from "vitepress";

export default defineConfig({
  base: "/",
  title: "Golden Palace",
  head: [
    [
      "script",
      {},
      "if (typeof location !== 'undefined' && location.protocol === 'http:' && location.hostname !== 'localhost') { location.replace('https:' + location.href.substring(location.protocol.length)); }",
    ],
  ],
  description:
    "A personal scripture memorization system built on Hebrew pictographs, gematria, PAO library, and mind palace architecture.",

  themeConfig: {
    nav: [
      { text: "Home", link: "/" },
      { text: "Alphabet", link: "/alphabet/" },
      { text: "Techniques", link: "/techniques/" },
      { text: "Books", link: "/books/" },
      { text: "Gematria", link: "/gematria/" },
      { text: "Tools", link: "/tools/" },
      { text: "GitHub", link: "https://github.com/njncalub/golden-palace" },
    ],

    sidebar: [
      {
        text: "Introduction",
        collapsed: false,
        items: [{ text: "What Is This?", link: "/" }],
      },
      {
        text: "Hebrew Alphabet",
        collapsed: true,
        items: [
          { text: "Getting Started", link: "/alphabet/" },
          { text: "01 - א - Aleph (#1)", link: "/alphabet/01-aleph" },
          { text: "02 - ב - Bet (#2)", link: "/alphabet/02-bet" },
          { text: "03 - ג - Gimel (#3)", link: "/alphabet/03-gimel" },
          { text: "04 - ד - Dalet (#4)", link: "/alphabet/04-dalet" },
          { text: "05 - ה - Hey (#5)", link: "/alphabet/05-hey" },
          { text: "06 - ו - Vav (#6)", link: "/alphabet/06-vav" },
          { text: "07 - ז - Zayin (#7)", link: "/alphabet/07-zayin" },
          { text: "08 - ח - Chet (#8)", link: "/alphabet/08-chet" },
          { text: "09 - ט - Tet (#9)", link: "/alphabet/09-tet" },
          { text: "10 - י - Yod (#10)", link: "/alphabet/10-yod" },
          { text: "11 - כ - Kaf (#20)", link: "/alphabet/11-kaf" },
          { text: "12 - ל - Lamed (#30)", link: "/alphabet/12-lamed" },
          { text: "13 - מ - Mem (#40)", link: "/alphabet/13-mem" },
          { text: "14 - נ - Nun (#50)", link: "/alphabet/14-nun" },
          { text: "15 - ס - Samech (#60)", link: "/alphabet/15-samech" },
          { text: "16 - ע - Ayin (#70)", link: "/alphabet/16-ayin" },
          { text: "17 - פ - Pey (#80)", link: "/alphabet/17-pey" },
          { text: "18 - צ - Tzadi (#90)", link: "/alphabet/18-tzadi" },
          { text: "19 - ק - Kof (#100)", link: "/alphabet/19-kof" },
          { text: "20 - ר - Resh (#200)", link: "/alphabet/20-resh" },
          { text: "21 - ש - Shin (#300)", link: "/alphabet/21-shin" },
          { text: "22 - ת - Tav (#400)", link: "/alphabet/22-tav" },
        ],
      },
      {
        text: "PAO Library",
        collapsed: true,
        items: [
          { text: "Overview", link: "/pao/" },
          {
            text: "00-09",
            collapsed: true,
            items: [
              { text: "00 - God (the LORD)", link: "/pao/00-god-over-waters" },
              { text: "01 - Adam", link: "/pao/01-adam" },
              { text: "02 - David", link: "/pao/02-david" },
              { text: "03 - Abraham", link: "/pao/03-abraham" },
              { text: "04 - Noah", link: "/pao/04-noah" },
              {
                text: "05 - The boy (five loaves)",
                link: "/pao/05-boy-with-loaves",
              },
              {
                text: "06 - The repentant thief",
                link: "/pao/06-repentant-thief",
              },
              { text: "07 - Joshua", link: "/pao/07-joshua" },
              { text: "08 - Isaac", link: "/pao/08-isaac" },
              { text: "09 - Hezekiah", link: "/pao/09-hezekiah" },
            ],
          },
          {
            text: "10-19",
            collapsed: true,
            items: [
              { text: "10 - Aaron", link: "/pao/10-aaron" },
              {
                text: "11 - Joseph (son of Jacob)",
                link: "/pao/11-joseph-son-of-jacob",
              },
              {
                text: "12 - James (son of Zebedee)",
                link: "/pao/12-james-son-of-zebedee",
              },
              {
                text: "13 - The Good Samaritan",
                link: "/pao/13-good-samaritan",
              },
              {
                text: "14 - The Israelite (Passover)",
                link: "/pao/14-israelite-passover",
              },
              { text: "15 - Heman (singer)", link: "/pao/15-heman" },
              { text: "16 - Thomas", link: "/pao/16-thomas" },
              { text: "17 - Japheth", link: "/pao/17-japheth" },
              { text: "18 - Lazarus", link: "/pao/18-lazarus" },
              { text: "19 - Melchizedek", link: "/pao/19-melchizedek" },
            ],
          },
          {
            text: "20-29",
            collapsed: true,
            items: [
              { text: "20 - Bezalel", link: "/pao/20-bezalel" },
              { text: "21 - Jacob", link: "/pao/21-jacob" },
              { text: "22 - Ezra", link: "/pao/22-ezra" },
              { text: "23 - Boaz", link: "/pao/23-boaz" },
              {
                text: "24 - An elder (Revelation)",
                link: "/pao/24-elder-revelation",
              },
              { text: "25 - Simeon", link: "/pao/25-simeon" },
              {
                text: "26 - The Angel of the LORD",
                link: "/pao/26-angel-of-the-lord",
              },
              { text: "27 - Stephen", link: "/pao/27-stephen" },
              { text: "28 - Nicodemus", link: "/pao/28-nicodemus" },
              { text: "29 - Joel (prophet)", link: "/pao/29-joel" },
            ],
          },
          {
            text: "30-39",
            collapsed: true,
            items: [
              { text: "30 - Judas Iscariot", link: "/pao/30-judas-iscariot" },
              {
                text: "31 - The virtuous woman",
                link: "/pao/31-virtuous-woman",
              },
              { text: "32 - Jonah", link: "/pao/32-jonah" },
              { text: "33 - Jesus", link: "/pao/33-jesus" },
              {
                text: "34 - The woman at the well",
                link: "/pao/34-woman-at-the-well",
              },
              { text: "35 - Habakkuk", link: "/pao/35-habakkuk" },
              { text: "36 - Zephaniah", link: "/pao/36-zephaniah" },
              { text: "37 - Joseph (in Egypt)", link: "/pao/37-joseph-egypt" },
              {
                text: "38 - Zechariah (father of John)",
                link: "/pao/38-zechariah-father-of-john",
              },
              { text: "39 - Malachi", link: "/pao/39-malachi" },
            ],
          },
          {
            text: "40-49",
            collapsed: true,
            items: [
              { text: "40 - Moses", link: "/pao/40-moses" },
              { text: "41 - Mark (John Mark)", link: "/pao/41-mark" },
              { text: "42 - Luke", link: "/pao/42-luke" },
              { text: "43 - John (apostle)", link: "/pao/43-john" },
              { text: "44 - Peter", link: "/pao/44-peter" },
              { text: "45 - Paul", link: "/pao/45-paul" },
              { text: "46 - Apollos", link: "/pao/46-apollos" },
              { text: "47 - Timothy", link: "/pao/47-timothy" },
              { text: "48 - Barnabas", link: "/pao/48-barnabas" },
              { text: "49 - Tychicus", link: "/pao/49-tychicus" },
            ],
          },
          {
            text: "50-59",
            collapsed: true,
            items: [
              { text: "50 - Epaphroditus", link: "/pao/50-epaphroditus" },
              { text: "51 - Onesimus", link: "/pao/51-onesimus" },
              { text: "52 - Silas", link: "/pao/52-silas" },
              {
                text: "53 - The man of lawlessness",
                link: "/pao/53-man-of-lawlessness",
              },
              { text: "54 - Eunice", link: "/pao/54-eunice" },
              { text: "55 - Lois", link: "/pao/55-lois" },
              { text: "56 - Titus", link: "/pao/56-titus" },
              { text: "57 - Philemon", link: "/pao/57-philemon" },
              {
                text: "58 - The writer of Hebrews",
                link: "/pao/58-writer-of-hebrews",
              },
              {
                text: "59 - James (brother of Lord)",
                link: "/pao/59-james-brother-of-lord",
              },
            ],
          },
          {
            text: "60-69",
            collapsed: true,
            items: [
              { text: "60 - Silvanus", link: "/pao/60-silvanus" },
              { text: "61 - Demetrius", link: "/pao/61-demetrius" },
              {
                text: "62 - A believer (1 John)",
                link: "/pao/62-believer-1-john",
              },
              { text: "63 - The chosen lady", link: "/pao/63-chosen-lady" },
              { text: "64 - Gaius", link: "/pao/64-gaius" },
              { text: "65 - Jude", link: "/pao/65-jude" },
              {
                text: "66 - The angel of Revelation",
                link: "/pao/66-angel-of-revelation",
              },
              { text: "67 - Deborah", link: "/pao/67-deborah" },
              { text: "68 - Barak", link: "/pao/68-barak" },
              { text: "69 - Gideon", link: "/pao/69-gideon" },
            ],
          },
          {
            text: "70-79",
            collapsed: true,
            items: [
              { text: "70 - Eldad", link: "/pao/70-eldad" },
              { text: "71 - Elijah", link: "/pao/71-elijah" },
              { text: "72 - Elisha", link: "/pao/72-elisha" },
              { text: "73 - Isaiah", link: "/pao/73-isaiah" },
              { text: "74 - Jeremiah", link: "/pao/74-jeremiah" },
              { text: "75 - Daniel", link: "/pao/75-daniel" },
              { text: "76 - Ezekiel", link: "/pao/76-ezekiel" },
              { text: "77 - Samson", link: "/pao/77-samson" },
              { text: "78 - Samuel", link: "/pao/78-samuel" },
              { text: "79 - Esther", link: "/pao/79-esther" },
            ],
          },
          {
            text: "80-89",
            collapsed: true,
            items: [
              { text: "80 - Solomon", link: "/pao/80-solomon" },
              { text: "81 - Rachel", link: "/pao/81-rachel" },
              { text: "82 - Ruth", link: "/pao/82-ruth" },
              { text: "83 - Naomi", link: "/pao/83-naomi" },
              { text: "84 - Rahab", link: "/pao/84-rahab" },
              { text: "85 - Hannah", link: "/pao/85-hannah" },
              { text: "86 - Caleb", link: "/pao/86-caleb" },
              { text: "87 - Abigail", link: "/pao/87-abigail" },
              { text: "88 - Elizabeth", link: "/pao/88-elizabeth" },
              {
                text: "89 - Mary (mother of Jesus)",
                link: "/pao/89-mary-mother-of-jesus",
              },
            ],
          },
          {
            text: "90-99",
            collapsed: true,
            items: [
              { text: "90 - Dorcas (Tabitha)", link: "/pao/90-dorcas" },
              { text: "91 - Mary Magdalene", link: "/pao/91-mary-magdalene" },
              { text: "92 - Martha", link: "/pao/92-martha" },
              {
                text: "93 - Philip (evangelist)",
                link: "/pao/93-philip-evangelist",
              },
              { text: "94 - Cornelius", link: "/pao/94-cornelius" },
              { text: "95 - Zacchaeus", link: "/pao/95-zacchaeus" },
              { text: "96 - Bartimaeus", link: "/pao/96-bartimaeus" },
              { text: "97 - Andrew", link: "/pao/97-andrew" },
              { text: "98 - Nathanael", link: "/pao/98-nathanael" },
              { text: "99 - Matthew (Levi)", link: "/pao/99-matthew" },
            ],
          },
        ],
      },
      {
        text: "Books of the Bible",
        collapsed: true,
        items: [
          { text: "Overview", link: "/books/" },
          { text: "01 - Genesis", link: "/books/01-genesis" },
          { text: "02 - Exodus", link: "/books/02-exodus" },
          { text: "03 - Leviticus", link: "/books/03-leviticus" },
          { text: "04 - Numbers", link: "/books/04-numbers" },
          { text: "05 - Deuteronomy", link: "/books/05-deuteronomy" },
          { text: "06 - Joshua", link: "/books/06-joshua" },
          { text: "07 - Judges", link: "/books/07-judges" },
          { text: "08 - Ruth", link: "/books/08-ruth" },
          { text: "09 - 1 Samuel", link: "/books/09-1-samuel" },
          { text: "10 - 2 Samuel", link: "/books/10-2-samuel" },
          { text: "11 - 1 Kings", link: "/books/11-1-kings" },
          { text: "12 - 2 Kings", link: "/books/12-2-kings" },
          { text: "13 - 1 Chronicles", link: "/books/13-1-chronicles" },
          { text: "14 - 2 Chronicles", link: "/books/14-2-chronicles" },
          { text: "15 - Ezra", link: "/books/15-ezra" },
          { text: "16 - Nehemiah", link: "/books/16-nehemiah" },
          { text: "17 - Esther", link: "/books/17-esther" },
          { text: "18 - Job", link: "/books/18-job" },
          { text: "19 - Psalms", link: "/books/19-psalms" },
          { text: "20 - Proverbs", link: "/books/20-proverbs" },
          { text: "21 - Ecclesiastes", link: "/books/21-ecclesiastes" },
          { text: "22 - Song of Solomon", link: "/books/22-song-of-solomon" },
          { text: "23 - Isaiah", link: "/books/23-isaiah" },
          { text: "24 - Jeremiah", link: "/books/24-jeremiah" },
          { text: "25 - Lamentations", link: "/books/25-lamentations" },
          { text: "26 - Ezekiel", link: "/books/26-ezekiel" },
          { text: "27 - Daniel", link: "/books/27-daniel" },
          { text: "28 - Hosea", link: "/books/28-hosea" },
          { text: "29 - Joel", link: "/books/29-joel" },
          { text: "30 - Amos", link: "/books/30-amos" },
          { text: "31 - Obadiah", link: "/books/31-obadiah" },
          { text: "32 - Jonah", link: "/books/32-jonah" },
          { text: "33 - Micah", link: "/books/33-micah" },
          { text: "34 - Nahum", link: "/books/34-nahum" },
          { text: "35 - Habakkuk", link: "/books/35-habakkuk" },
          { text: "36 - Zephaniah", link: "/books/36-zephaniah" },
          { text: "37 - Haggai", link: "/books/37-haggai" },
          { text: "38 - Zechariah", link: "/books/38-zechariah" },
          { text: "39 - Malachi", link: "/books/39-malachi" },
          { text: "40 - Matthew", link: "/books/40-matthew" },
          { text: "41 - Mark", link: "/books/41-mark" },
          { text: "42 - Luke", link: "/books/42-luke" },
          { text: "43 - John", link: "/books/43-john" },
          { text: "44 - Acts", link: "/books/44-acts" },
          { text: "45 - Romans", link: "/books/45-romans" },
          { text: "46 - 1 Corinthians", link: "/books/46-1-corinthians" },
          { text: "47 - 2 Corinthians", link: "/books/47-2-corinthians" },
          { text: "48 - Galatians", link: "/books/48-galatians" },
          { text: "49 - Ephesians", link: "/books/49-ephesians" },
          { text: "50 - Philippians", link: "/books/50-philippians" },
          { text: "51 - Colossians", link: "/books/51-colossians" },
          { text: "52 - 1 Thessalonians", link: "/books/52-1-thessalonians" },
          { text: "53 - 2 Thessalonians", link: "/books/53-2-thessalonians" },
          { text: "54 - 1 Timothy", link: "/books/54-1-timothy" },
          { text: "55 - 2 Timothy", link: "/books/55-2-timothy" },
          { text: "56 - Titus", link: "/books/56-titus" },
          { text: "57 - Philemon", link: "/books/57-philemon" },
          { text: "58 - Hebrews", link: "/books/58-hebrews" },
          { text: "59 - James", link: "/books/59-james" },
          { text: "60 - 1 Peter", link: "/books/60-1-peter" },
          { text: "61 - 2 Peter", link: "/books/61-2-peter" },
          { text: "62 - 1 John", link: "/books/62-1-john" },
          { text: "63 - 2 John", link: "/books/63-2-john" },
          { text: "64 - 3 John", link: "/books/64-3-john" },
          { text: "65 - Jude", link: "/books/65-jude" },
          { text: "66 - Revelation", link: "/books/66-revelation" },
        ],
      },
      {
        text: "Memory Techniques",
        collapsed: true,
        items: [
          { text: "Overview", link: "/techniques/" },
          {
            text: "Verse Memorization (Word for Word)",
            link: "/techniques/verse-memorization",
          },
          { text: "Mind Palace", link: "/techniques/mind-palace" },
          { text: "PAO System", link: "/techniques/pao" },
          { text: "Hebrew Major System", link: "/techniques/major-system" },
          { text: "Spaced Repetition", link: "/techniques/spaced-repetition" },
          { text: "Gematria for Memory", link: "/techniques/gematria" },
        ],
      },
      {
        text: "Verses & Meditations",
        collapsed: false,
        items: [
          { text: "Verse Entries", link: "/verses/" },
          { text: "Visual Meditations", link: "/meditations/" },
        ],
      },
      {
        text: "Gematria Study",
        collapsed: false,
        items: [
          { text: "Getting Started", link: "/gematria/" },
          { text: "Discoveries", link: "/gematria/discoveries" },
        ],
      },
      {
        text: "Tools",
        collapsed: false,
        items: [
          { text: "Overview", link: "/tools/" },
          { text: "Prompts & Study Tools", link: "/tools/prompts" },
        ],
      },
    ],

    socialLinks: [
      { icon: "github", link: "https://github.com/njncalub/golden-palace" },
    ],

    footer: {
      message: "Built with VitePress",
      copyright: "",
    },
  },
});
